import customRichTextBlock from '../../blocks/reusable/custom-richtext-block.jsx';
import { namespace } from "../../blocks/helper-functions/constants";

export default function richTextBlocks() {
  // Reusable blocks
    const blocks = [
        {
            slug: 'paragraph',
            title: 'Paragraph',
            description: 'Write paragraphs',
            category: 'common',
            settings: ['core/bold', 'core/italic', 'core/link'],
            icon: 'editor-paragraph',
            placeholder: 'Start writing your paragraph',
            tagName: 'p',
            classes: ['paragraph'],
            transforms: ['paragraph-no-alignment'],
            parent: [`${namespace}/development`, `${namespace}/body-copy`],
        },
        {
            slug: 'paragraph-no-alignment',
            title: 'Paragraph',
            description: 'Write paragraphs',
            category: 'common',
            settings: ['core/bold', 'core/italic', 'core/link'],
            icon: 'editor-paragraph',
            placeholder: 'Start writing your paragraph',
            tagName: 'p',
            classes: ['paragraph'],
            alignment: false,
            transforms: ['paragraph'],
            parent: [`${namespace}/accordion-row`, `${namespace}/feature-strip`, `${namespace}/image-text`, `${namespace}/page-strip-graphic`, `${namespace}/page-strip`, `${namespace}/content-card`, `${namespace}/image-list`,   `${namespace}/testimonial-slide`, `${namespace}/milestone`]
        },
        {
            slug: 'headline',
            title: 'Headline',
            description: 'A page headline',
            category: 'common',
            icon: 'heading',
            placeholder: 'Start writing your header',
            classes: ['heading-one'],
            tagName: 'h1',
            blockSettings: true,
            parent: [`${namespace}/development`],
            transforms: ['paragraph', 'heading-one', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six'],
        },
        {
            slug: 'heading-one',
            title: 'Heading One',
            description: 'A top level header',
            category: 'common',
            icon: 'heading',
            placeholder: 'Start writing your header',
            classes: ['heading-one'],
            tagName: 'h1',
            blockSettings: true,
            parent: [`${namespace}/development`, `${namespace}/body-copy`],
            transforms: ['paragraph', 'heading-two', 'heading-three', 'heading-four', 'heading-five', 'heading-six'],
        },
        {
            slug: 'heading-two',
            title: 'Heading Two',
            description: 'A second level header',
            category: 'common',
            icon: 'heading',
            placeholder: 'Start writing your header',
            classes: ['heading-two'],
            tagName: 'h2',
            blockSettings: true,
            parent: [`${namespace}/development`, `${namespace}/body-copy`],
            transforms: ['paragraph', 'heading-one', 'heading-three', 'heading-four', 'heading-five'],
        },
        {
            slug: 'heading-three',
            title: 'Heading Three',
            description: 'A third level header',
            category: 'common',
            icon: 'heading',
            placeholder: 'Start writing your header',
            classes: ['heading-three'],
            tagName: 'h3',
            blockSettings: true,
            parent: [`${namespace}/development`, `${namespace}/body-copy`],
            transforms: ['paragraph', 'heading-one', 'heading-two', 'heading-four', 'heading-five'],
        },
        {
            slug: 'heading-four',
            title: 'Heading Four',
            description: 'A fourth level header',
            category: 'common',
            icon: 'heading',
            placeholder: 'Start writing your header',
            classes: ['heading-four'],
            tagName: 'h4',
            blockSettings: true,
            parent: [`${namespace}/development`, `${namespace}/body-copy`],
            transforms: ['paragraph', 'heading-one', 'heading-two', 'heading-three', 'heading-five'],
        },
        {
            slug: 'heading-five',
            title: 'Heading Five',
            description: 'A fifth level header',
            category: 'common',
            icon: 'heading',
            placeholder: 'Start writing your header',
            classes: ['heading-five'],
            tagName: 'h5',
            blockSettings: true,
            parent: [`${namespace}/development`, `${namespace}/body-copy`],
            transforms: ['paragraph', 'heading-one', 'heading-two', 'heading-three', 'heading-four'],
        },
        {
            slug: 'heading-six',
            title: 'Heading Six',
            description: 'A sixth level header',
            category: 'common',
            icon: 'heading',
            placeholder: 'Start writing your header',
            classes: ['heading-six'],
            tagName: 'h6',
            blockSettings: true,
            parent: [`${namespace}/development`, `${namespace}/body-copy`],
            transforms: ['paragraph', 'heading-one', 'heading-two', 'heading-three', 'heading-four', 'heading-five'],
        },
        {
            slug: 'caption',
            title: 'Caption',
            description: 'An image caption',
            category: 'common',
            icon: 'editor-paragraph',
            placeholder: 'Start writing your caption',
            classes: ['caption'],
            settings: ['core/bold', 'core/italic', 'core/link'],
            tagName: 'p',
            blockSettings: true,
            parent: [`${namespace}/development`],
            transforms: ['paragraph', 'heading-one', 'heading-two', 'heading-three', 'heading-four', 'heading-five'],
        },
        {
            slug: 'btn',
            title: 'Button',
            description: 'A button',
            category: 'common',
            icon: 'button',
            placeholder: 'Write your button text',
            classes: ['btn'],
            tagName: 'button',
            blockSettings: true,
            parent: [`${namespace}/development`],
            transforms: ['paragraph', 'heading-one', 'heading-two', 'heading-three', 'heading-four'],
        },
        {
            slug: 'eyebrow',
            title: 'Eyebrow',
            description: 'An eyebrow',
            category: 'common',
            icon: 'visibility',
            placeholder: 'Write your eyebrow text',
            classes: ['eyebrow'],
            tagName: 'div',
            settings: [],
            parent: [`${namespace}/development`],
            transforms: ['paragraph', 'heading-one', 'heading-two', 'heading-three', 'heading-four'],
        }

    ];

    blocks.forEach((block) => {
        customRichTextBlock(block);
    })
}